// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $post from "./routes/post.tsx";
import * as $CategoriasMobile from "./islands/CategoriasMobile.tsx";
import * as $MenuMobile from "./islands/MenuMobile.tsx";
import * as $MyIsland from "./islands/MyIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/post.tsx": $post,
  },
  islands: {
    "./islands/CategoriasMobile.tsx": $CategoriasMobile,
    "./islands/MenuMobile.tsx": $MenuMobile,
    "./islands/MyIsland.tsx": $MyIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
